### ISSUE TITLE
ToggleTVSet Upgrade broke TVs

### ISSUE THREAD

**Issue by pmacswebteam** [Jako/ToggleTVSet#1]
Hello,

After upgrading to ToggleTVSet 1.2.1-pl, the first TV that we created using ToggleTVSet works fine, however, all other TVs using ToggleTVSet are broken. When using the single select TV, the proper TV fields associated with the single select TV choice do not display.  No fields display and the user is left with a blank screen.

**Comment by pmacswebteam** [comment]
To be more specific, whichever ID is listed FIRST within the "Toggling Template Variables" System Setting is the only TV that works properly. We currently have 4 IDs listing for this setting.

**Comment by Jako** [comment]
Fixed with 1.2.2
