### ISSUE TITLE
ToggleTVSet broken on modx 2.8.4

### ISSUE THREAD

**Issue by mbaumrucker** [Jako/ToggleTVSet#11]
Hi,

I'm using ToggleTVSet version 2.0.0 on Modx 2.8.4.

The first time the toggle works fine and the tv's are showing/hiding as expected, but after saving and reloading the page/resource the tv's are hidden again. When I look at the error log, Ext JS is throwing this error:

![image](https://user-images.githubusercontent.com/1801040/183053351-c81395dc-a003-4649-9e56-3601ce54fc2c.png)

![image](https://user-images.githubusercontent.com/1801040/183054982-fc7674a0-a3bb-4cb0-9b7a-14681239e9c0.png)

I'm using Chome latest version (104.0.5112.79) on different platforms (Windows and OSX).

**Comment by jmacdonald-spectacle** [comment]
I see this occasionally in MODX 3.01.

It's hard to see why it's happening and hard to reproduce.

I get the same error as above in Chrome's console.

**Comment by jmacdonald-spectacle** [comment]
Actually, I *can* reproduce it.

I have a custom plugin that compiles scss. When it needs to compile, I see the error (and the tvs). Otherwise it seems to work fine.

Both plugins listen to the ```OnManagerPageBeforeRender``` event, so I changed the priority on *my* plugin, but no luck.

**Comment by Jako** [comment]
Can you send me the plugin or the basic stripped code? Maybe there is an issue inside. I don't get a reason, why #modx-panel-resource can't be found in the HTML code.

**Comment by jmacdonald-spectacle** [comment]
Hi @Jako.

 I won't send you my plugin. It's a house of cards!

Basically, it runs scssphp server and installs it in the manager with regClientStartupHTMLBlock. Compiling scss takes a little time, so this may be a timing issue.

To be sure, I disabled all plugins except mine and ToggleTVSet, plus I made a new resource using the (empty) template with no tvs. It's the same issue: works fine except when scss needs compiling.

Finally, I tested on a MODX 2.8.4 install with a similar setup -- no issue.

So, this is my problem and I'm willing to live with it because it's predictable and the users will likely never see it.

It's possible the OP has a similar time-intensive plugin.

Let me know if you want me to test something else.

**Comment by Jako** [comment]
Can you send or post the code difference when the scssphp server is invoked or not invoked? Do you have some 404 issues then loading the manager page? For whatever reason, the #modx-panel-resource section can't be found at that moment. So it must be some code that deletes that section or the section is created too late by javascript then.

**Comment by jmacdonald-spectacle** [comment]
Hey @Jako,

The plugin code is the same. The scssphp server executes when there's a change to the scss file. Any change at all -- I can trigger it by adding or removing a space.

I made a simplified plugin and scss file. I don't get an error running a simple style, but importing does get an error. As I said, it seems to be a timing problem.

I'm setting up a test environment that I will share with you. How can I send you the credentials?

**Comment by jmacdonald-spectacle** [comment]
Assuming I've sent you the credentials for my modx3 test site, go ahead and change whatever you want.

The plugin is called 'ManagerAdjustments' and just loads the stylesheet.

The scss.php and simple.scss files are in the assets folder. 

Loading the one resource, you'll see that #modx-panel-resource is a light green colour. That means the stylesheet is loading. If you change the simple.scss in a small way, you'll see the error in Chrome's console.log. If you comment-out the import, you won't get the error at all.

As I've said, I'm personally okay with how this works, but am providing this in case it helps you solve the OP's problem.

Let me know if you need anything else.

**Comment by Jako** [comment]
Please try the patch in this file: https://github.com/Jako/ToggleTVSet/commit/fbbc5c330768512d2dfe41317fa67891450b4531#diff-d0b304b93d07f737ba0fd126555ab7e31be711ac03ed6bbf9b75cb515a6016e7

**Comment by mbaumrucker** [comment]
> Please try the patch in this file: [fbbc5c3#diff-d0b304b93d07f737ba0fd126555ab7e31be711ac03ed6bbf9b75cb515a6016e7](https://github.com/Jako/ToggleTVSet/commit/fbbc5c330768512d2dfe41317fa67891450b4531#diff-d0b304b93d07f737ba0fd126555ab7e31be711ac03ed6bbf9b75cb515a6016e7)

Tried the patch and it seems to work now. Error is gone and toggles as expected.

When will this version be released?

**Comment by jmacdonald-spectacle** [comment]
Working great in MODX 3.0.1. Thanks @Jako

**Comment by Jako** [comment]
2.0.1 is there.
