### ISSUE TITLE
ToggleTVSet 2.0.1 requires PHP 7.4 but has PHP 7.2 listed as dependency

### ISSUE THREAD

**Issue by pmacswebteam** [Jako/ToggleTVSet#12]
When testing ToggleTVSet 2.0.1 we were getting: 

`( ! ) Parse error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in [path_to_core]/core/components/toggletvset/src/Snippets/Snippet.php on line 35`

It seems like the trouble is that we are running PHP 7.3.x and Snippet.php uses [Typed Properties which were introduced in PHP 7.4](https://www.php.net/manual/en/migration74.new-features.php) on line [35 and 41](https://github.com/Jako/ToggleTVSet/blob/master/core/components/toggletvset/src/Snippets/Snippet.php#L35).

We'll be upgrading PHP everywhere soon but wanted to report this in the interest of being helpful.

**Comment by Jako** [comment]
You can patch both lines. In the next version these typed properties are removed.

**Comment by pmacswebteam** [comment]
Thank you!

**Comment by Jako** [comment]
Fixed with 2.0.2
