### ISSUE TITLE
ToggleTVSet-2.0.4 Temporarily Displays Previous Options After Saving Resource

### ISSUE THREAD

**Issue by pmacswebteam** [Jako/ToggleTVSet#15]
ToggleTVSet-2.0.4 has an issue where if you toggle an option and save the resource, the ToggleTVSet shows the previously set option instead. On page refresh, the ToggleTVSet then displays everything as normal.

Our apologies as this issue may have been caused by the solution proposed here https://github.com/Jako/ToggleTVSet/issues/13

EDIT: We also have not been able to reproduce our original issue, so reverting the timeout may be fine.

**Comment by Jako** [comment]
Please check the release canditate of 2.0.5 with the package file: https://github.com/Jako/ToggleTVSet/raw/master/_packages/toggletvset-2.0.5-rc1.transport.zip

**Comment by pmacswebteam** [comment]
The issue is resolved in the release candidate of 2.0.5. Thank you Jako!
