### ISSUE TITLE
getTVLabel empty variable(s) cause error

### ISSUE THREAD

**Issue by pmacswebteam** [Jako/ToggleTVSet#2]
Hello,

When using ToggleTVSet and pdoTools packages on the same site, the following error occurs when trying to view the site:

Fatal error: Call to a member function get() on a non-object in /home/cms/modx-cores/pdotools/cache/pdotools/includes/elements/modsnippet/39.include.cache.php on line 18

We believe this to be due to the fact that one or more of the variables used in the "getTVLabel" are empty.  In order to solve this, we altered the code by adding the following if !empty statements (see attached file).
[getTVLabel-updatedSnippet.txt](https://github.com/Jako/ToggleTVSet/files/167179/getTVLabel-updatedSnippet.txt)

Could this, or something similar, be adjusted within the package in order to ensure that the error mentioned above goes away?

Thanks!

**Comment by Jako** [comment]
Could you give an example call of the with the output filter?

Do you call it with `[[myTV:getTVLabel]]` or with `[[myTV:getTVLabel=`myTV`]]`? The second call does not work, because that way the TV name is stripped totally. The propery it is only for removing a prefix.

**Comment by Jako** [comment]
The Issue can't be created by pdoTools according to @bezumkin. The check is now done right. But I think you are doing a wrong call with invalid getTVLabel modifier options.

**Comment by pmacswebteam** [comment]
Hi Jako,

We call ToggleTVSet like this:

`[[$[[*myYV:getTVLabel]]]]`

**Comment by Jako** [comment]
That way you get the value of myTV for the current resource and not for the listed resource by pdoResources. You have to use
```
[[$[[+myTV:getTVLabel]]]]
```

**Comment by pmacswebteam** [comment]
thank you for pointing this out!
