### ISSUE TITLE
TV's are not hidden on page load in Manager

### ISSUE THREAD

**Issue by kinaz** [Jako/ToggleTVSet#3]
Hi,

version: 1.2.2-pl
php: 5.3.29

core/components/toggletvset/model/toggletvset/toggletvset.class.php, line 98 and line 115

After this line `$hidetvs = array_unique($hidetvs);` `json_encode($hidetvs)` returns an associative array.
The javascript snippet appended to `<head>` then prints the wrong values and all tv's are visible regardless of the selection.

`$hidetvs = array_values(array_unique($hidetvs));` fixes it.

**Comment by Jako** [comment]
Fixed with 10540c420fd3d5c6e29bdf880696eb7f37c1dd1d

Thanks for reporting!
