### ISSUE TITLE
ToggleSet out of sync when a new TV is added

### ISSUE THREAD

**Issue by jonleverrier** [Jako/ToggleTVSet#5]
I have a TV Toggle setup like this;

```
Please select...==||Event==43,58,49,47,48,42,12,13,52,53,54,51,56,57,55,11,15,16,17,18,44,45,46||Coming Soon==12,16
```
It's assigned and set to over 200 resources. If I need to add a new TV id to the above toggle set, this happens;

<img width="424" alt="screen shot 2017-03-09 at 21 16 11" src="https://cloud.githubusercontent.com/assets/2373940/23768872/b55f5ec8-050d-11e7-90fd-7d58eb6dfe13.png">

Resources that were set to "Event" are now set to "43,58,49,47,48,42,12,13,52,53,54,51,56,57,55,11,15,16,17,18,44,45,46". The TV ID's disappear from the drop down, if I reselect "Event" and save. I don't fancy having todo this for more than 200 resources.

I have tried clearing my cache. Any thoughts?

**Comment by jonleverrier** [comment]
this is default behaviour of MODX

**Comment by Jako** [comment]
Maybe you should change 

```
Please select...==||Event==43,58,49,47,48,42,12,13,52,53,54,51,56,57,55,11,15,16,17,18,44,45,46||Coming Soon==12,16
```

 to

```
Please select...==||Event==[[$TVSetEvent]]||Coming Soon==[[$TVSetComing]]
```

and fill the Chunks with the ID list. Not sure if that works everywhere.

**Comment by jonleverrier** [comment]
@Jako - nice work around, but i'll run into the same problem if I have to add another group in addition to the ones that are already there (event & coming soon).

**Comment by jonleverrier** [comment]
OK - i've tried replacing the TV values with chunks like you suggested, but it appears that the info inside the chunks aren't being parsed

**Comment by jonleverrier** [comment]
Hi @Jako - any ideas if a fix for this will be rolled out anytime soon?

**Comment by Jako** [comment]
The values will be saved unparsed into the database as [[$TVSetEvent]] etc. They will be parsed later during rendering the page, when the TV is used.

You can't have @SELECT inside i.e. the TVSetEvent chunk but a snippet call that returns a comma separated list of IDs.
